name: cycle_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  google_fonts: ^4.0.4  # 최신 버전 사용
  flutter_native_splash: ^2.3.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.2.5
  location: ^4.4.0
  flutter_polyline_points: ^1.0.0
  geolocator: ^9.0.2
  flutter_local_notifications: ^9.1.5
  kakao_flutter_sdk: ^1.4.1
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  http: ^0.13.5
  url_launcher: ^6.0.20  # 새로 추가된 의존성
  image_picker: ^1.0.7
  flutter_svg: ^2.0.9
  geocoding: ^2.1.0
  flutter_dotenv: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/bike-day.png
    - assets/kakao_login_logo.png
    - .env



flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/bike-day.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/bike-day.png"

flutter_native_splash:
  image: assets/bike-day.png
  color: "#42a5f5"
  android_12:
    image: assets/bike-day.png
    icon_background_color: "#42a5f5"